import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ScrollToTopButton from "@/components/Scroll";
import Experience from "@/components/Experience";
import { ThemeProvider } from "next-themes";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap', // 'swap' is generally a good choice for a fast display
  variable: '--font-poppins', // You can use this with Tailwind CSS
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  suppressHydrationWarning>
      <body
        className={`${poppins.variable} ${poppins.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <Header />
          <main className="flex-1 w-full">{children}</main>
        <ScrollToTopButton />
        <Experience />
        <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
